'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCollectionSaving
    Public Property ReceiptNo As String
    Public Property SavingsAccNo As String
    Public Property ReceiptDate As Date
    Public Property WithdrawAmt As Nullable(Of Decimal)
    Public Property DepositAmt As Nullable(Of Decimal)
    Public Property CollectedBy As String

    Public Overridable Property tblSavingsAcc As tblSavingsAcc

End Class
