'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCustomer
    Public Property CustID As String
    Public Property CustFname As String
    Public Property CustMname As String
    Public Property CustLname As String
    Public Property CustSname As String
    Public Property CustAdd As String
    Public Property CustContact As String
    Public Property Center As String
    Public Property CustOcc As String
    Public Property CustDOB As String
    Public Property CustDOM As String
    Public Property CustSpouse As String
    Public Property CustBplace As String
    Public Property CustStatus As String

    Public Overridable Property tblCollectionIns As ICollection(Of tblCollectionIn) = New HashSet(Of tblCollectionIn)
    Public Overridable Property tblCollMiscs As ICollection(Of tblCollMisc) = New HashSet(Of tblCollMisc)
    Public Overridable Property tblInsurances As ICollection(Of tblInsurance) = New HashSet(Of tblInsurance)
    Public Overridable Property tblLoanReleases As ICollection(Of tblLoanRelease) = New HashSet(Of tblLoanRelease)
    Public Overridable Property tblSavingsAcc As tblSavingsAcc

End Class
