'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCollMisc
    Public Property ReceiptNo As String
    Public Property CustID As String
    Public Property ReceiptDate As Date
    Public Property Passbook As Nullable(Of Decimal)
    Public Property Others As Nullable(Of Decimal)
    Public Property CollectedBy As String

    Public Overridable Property tblCustomer As tblCustomer

End Class
