'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCollectionLoan
    Public Property ReceiptNo As String
    Public Property LoanAccNo As String
    Public Property ReceiptDate As Date
    Public Property PrincipalAmt As Decimal
    Public Property IntAmt As Decimal
    Public Property PenaltyAmt As Decimal
    Public Property PenaltyPaid As Decimal
    Public Property CollectedBy As String

    Public Overridable Property tblLoanRelease As tblLoanRelease
    Public Overridable Property tblLoanRelease1 As tblLoanRelease

End Class
