'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblLoanRelease
    Public Property LoanAccNo As String
    Public Property CustID As String
    Public Property DateRelease As Date
    Public Property Principal As Decimal
    Public Property Interest As Decimal
    Public Property ProcFee As Decimal
    Public Property Terms As Decimal
    Public Property LoanType As String
    Public Property Maturity As Date

    Public Overridable Property tblCollectionLoans As ICollection(Of tblCollectionLoan) = New HashSet(Of tblCollectionLoan)
    Public Overridable Property tblCollectionLoans1 As ICollection(Of tblCollectionLoan) = New HashSet(Of tblCollectionLoan)
    Public Overridable Property tblCustomer As tblCustomer

End Class
