'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblSavingsAcc
    Public Property SavAccNo As String
    Public Property AccBal As Decimal
    Public Property AccOpen As Date
    Public Property AccClose As Date

    Public Overridable Property tblCollectionSavings As ICollection(Of tblCollectionSaving) = New HashSet(Of tblCollectionSaving)
    Public Overridable Property tblCustomer As tblCustomer

End Class
